# -*- coding: utf-8 -*-
"""edge3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_pfnwIz-ieMxtDcScN4teZ-bU6LHVzY
"""

import heapq
import time 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

edges = []                        #edge servers 
iots=[]                           #iots devices
for i in range(0,4):             
    edges.append("edge" + str(i))                 
    
    
for i in range(0,20):
    iots.append("iot" + str(i+4))
    
print("iots: ",iots)
print("edges: ",edges)

### INPUTS###

avg_pkt_size=8000       #packet size in bits
max_thres=85000*avg_pkt_size # bits 85000*8000 =680000000 bits
                             #maximum load that one edge can take is "max_thres"




frequency=2.4*10**9    # standard frequency of AODV protocol
datarate= 54*10**6     # standard datarate at which data can be transmitted,
                       #unit of datarate bits/sec
# Different Variables , list , dictionary are initialized here                       
extraload = {"edge1" : [], "edge2" : [],"edge3" : [],"edge4" : []}  #extraload on edges, 
                                                                    #exceeding, maximum threshold  
edgelist = ["edge1","edge2","edge3","edge4"]     
remaining_capacity_ofedges = {}                  #remaining space
t0 = 0 # starting time   

print("\n")
 

class edge3:
  ##### edge 3  ########
  tjoin_edge3 = [27,38,39]   #joining times of nodes to edge3 
  tsend_edge3 = []               #time to send  to edge3 from nodes/iots


  for i in range(0,3):
    
    tsend_edge3.append(random.randint(1,300*10**6)/datarate)
    
    
  print("time taken to send/receive data to edge3:",tsend_edge3)    
    

  tfinal_edge3 = []                           #final time when tcp connection stops
  for i in range(0,3):
    tfinal_edge3.append(tsend_edge3[i] + tjoin_edge3[i])
    
  load_edge3 = []                      #load due to each node on edge3

  print("final time of iots which are connected to edge3: ",tfinal_edge3)

  for i in range(0,3):
    load_edge3.append(int(datarate*(tfinal_edge3[i]-tjoin_edge3[i])))

  print("iots to connect to edge3: ",load_edge3)
               #workload on edge3     


    

  total_load_edge3 = 0            #summation of all loads contributed by all nodes connected to edge1
  for i in range(0,3):
    if(total_load_edge3 < max_thres and load_edge3[i] <= (max_thres - total_load_edge3)):
      total_load_edge3 += load_edge3[i]
      
    else:
        print("load exceeded on edge , try connceting to some other edge")
        extraload["edge3"].append(load_edge3[i]) 
    

  print("extraload ",extraload)
  edgeload = total_load_edge3
    
    
  print("total load of iots which are connected to edge3: ",total_load_edge3)    
  print("maximum threshold of edge3: ",max_thres)
  load3 = max_thres - total_load_edge3
  print("\n")